### ISSUE TITLE
Banco de dados

### ISSUE THREAD

**Issue by willianwt** [willianwt/Anota#4]
O aplicativo utiliza o Firebase Realtime Database como banco de dados.
É um banco NoSQL da Google.

Precisamos definir a modelagem para a questão de curso/semestre/disciplinas de cada usuário registrado.

**Comment by willianwt** [comment]
- buscas e filtros

**Comment by antonylucas** [comment]
Sobre a questão do retorno do dado é possível ser feito segundo os métodos do link em anexo, não encontrei forma de tratar o retorno de vários nós por consulta.

https://firebase.google.com/docs/database/admin/retrieve-data?hl=pt-br

**Comment by antonylucas** [comment]
Verificar regras de segurança do banco de dados; analisar melhor forma de implementar. Até o momento as regras estão públicas.

![image](https://user-images.githubusercontent.com/38044066/65147790-40452900-d9f5-11e9-97b5-7e216c8c6122.png)

**Comment by antonylucas** [comment]
A regra de segurança a seguir foi implementada na base de dados para garantir que cada usuário autenticado receba um nó pessoal em /users/$user_id, em que $user_id seja o código do usuário recebido por meio do F. Authentication; garante assim que o usuário consiga fazer leitura e gravação deste que ele esteja autenticado no app.

![screenshot](https://user-images.githubusercontent.com/38044066/65709073-5a6eaf00-e066-11e9-83de-9e1de9cf160a.png)


<h2> Simulação feita para validar a não gravação caso o user não esteja autenticado. </h2>

![screenshot](https://user-images.githubusercontent.com/38044066/65709123-770ae700-e066-11e9-8fc4-c3e908f1083d.png)

@willianwt Por gentileza validar as alterações para o caso de nova demonstração na aula de hoje ao professor.

**Comment by willianwt** [comment]
feito!
